### ISSUE TITLE
Offline Server

### ISSUE THREAD

**Issue by M3nin0** [satgateway/sentinel2-search-api#3]
Hello, the project is very interesting, but today when I went to perform a test in your live, the server presented problems. Other than that I have a doubt, the worker, when I go to configure it, can I define a list of tiles? or just by dates?

 Thank help.

PS: Sorry for my english

**Comment by brycejohnston** [comment]
@M3nin0 thanks for posting the issue. I just brought the app back up at https://sentinel2.satgateway.com but it has a backlog of jobs to import tile data from Feb 2018 - April 2018, but you can still query anything From early Feb 2018 back to beginning.

The [sentinel_worker](https://github.com/beaorn/sentinel2-search-api/blob/master/app/workers/sentinel_worker.rb) is designed to run daily imports of tile metadata from AWS into the app's local database that this app's API exposes. Basically the app is set to run daily tasks daily to import new tile data and keep an up to date catalog of everything in AWS to make it easy for other apps or scripts to query against to find dates of tiles they want to download for processing. 

So for example if you have another application, script, etc and you wanted to find and download tile data for MGRS 23KMQ, you can query the API of the app in multiple ways to get the info you want:

### Get all tiles for 23KMQ
https://sentinel2.satgateway.com/api/v1/tiles?mgrs=23KMQ

### Get all tiles for 23KMQ with date >= 2017-01-01
https://sentinel2.satgateway.com/api/v1/tiles?mgrs=36RUU&start_date=2017-01-01

### Get all tiles for 23KMQ with date <= 2017-10-15
https://sentinel2.satgateway.com/api/v1/tiles?mgrs=36RUU&end_date=2017-10-15

### Get all tiles for 23KMQ between 2017-01-01 and 2017-10-15
https://sentinel2.satgateway.com/api/v1/tiles?mgrs=36RUU&start_date=2017-01-01&end_date=2017-10-15

### Get all tiles for 23KMQ with <= 50% cloud coverage
https://sentinel2.satgateway.com/api/v1/tiles?mgrs=36RUU&cloud_max=50

### Get all tiles for 23KMQ with >= 10% data coverage
https://sentinel2.satgateway.com/api/v1/tiles?mgrs=36RUU&data_min=10

These queries will return data in the following format:
```json
[

    {
        "mgrs_grid_name": "23KMQ",
        "utm_zone": 23,
        "latitude_band": "K",
        "grid_square": "MQ",
        "path": "tiles/23/K/MQ/2018/2/1/0",
        "date": "2018-02-01",
        "timestamp": "2018-02-01T13:12:35.461Z",
        "epsg": "32723",
        "product_name": "S2B_MSIL1C_20180201T131239_N0206_R138_T23KMQ_20180201T135144",
        "product_path": "products/2018/2/1/S2B_MSIL1C_20180201T131239_N0206_R138_T23KMQ_20180201T135144",
        "data_coverage_percentage": "100.0",
        "cloudy_pixel_percentage": "8.77",
        "thumbnail": "https://sentinel-s2-l1c.s3.amazonaws.com/tiles/23/K/MQ/2018/2/1/0/preview.jpg"
    },
]
```

The path that is returned can be used to build a URL for the app querying and parsing JSON from the API to use to fetch the desired files, http://sentinel-s2-l1c.s3.amazonaws.com/tiles/ + path/ + filename, like: http://sentinel-s2-l1c.s3.amazonaws.com/tiles/23/K/MQ/2018/2/1/0/B01.jp2

Let me know if that helps or if I misunderstood your question.

**Comment by M3nin0** [comment]
Yes, your explanation helped me to better understand how the API works, it was very good, congratulations. And thanks for putting her back online again, I'll do the query tests you mentioned above. Thank you
